# Generated by Django 5.2 on 2025-04-22 08:36

import meetings_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(default='new Meeting', max_length=100)),
                ('meeting_summary', models.CharField(blank=True, max_length=2000, null=True)),
                ('meeting_key_points', models.JSONField(blank=True, null=True)),
                ('meeting_is_favourite', models.BooleanField(default=False)),
                ('meeting_created_on', models.DateTimeField(auto_now_add=True)),
                ('meeting_audio_recording', models.FileField(null=True, upload_to='meeting_audios/', validators=[meetings_api.models.validate_audiofile])),
                ('meeting_plain_text', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
